config/routes.rb
Rails.application.routes.draw do
  resources :events
  resources :events
  resources :vacancies
  resources :customers
  resources :countries
  root to: 'welcome#index'
  devise_for :users
  resources :users
end

app/models/country.rb
class Country < ActiveRecord::Base
	validates :iso_code_2, length: { is: 2, too_long: "2 characters are mandatory" }
    validates :iso_code_3, length: { is: 3, too_long: "3 characters are mandatory" }
    validates_uniqueness_of :iso_code_2, :iso_code_3
    validates :name, uniqueness: { case_sensitive: false }
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  before_action :set_country, only: [:show, :edit, :update, :destroy]

  # GET /countries
  # GET /countries.json
  def index
    @countries = Country.all
  end

  # GET /countries/1
  # GET /countries/1.json
  def show
  end

  # GET /countries/new
  def new
    @country = Country.new
  end

  # GET /countries/1/edit
  def edit
  end

  # POST /countries
  # POST /countries.json
  def create
    @country = Country.new(country_params)

    respond_to do |format|
      if @country.save
        format.html { redirect_to @country, notice: 'Country was successfully created.' }
        format.json { render :show, status: :created, location: @country }
      else
        format.html { render :new }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /countries/1
  # PATCH/PUT /countries/1.json
  def update
    respond_to do |format|
      if @country.update(country_params)
        format.html { redirect_to @country, notice: 'Country was successfully updated.' }
        format.json { render :show, status: :ok, location: @country }
      else
        format.html { render :edit }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /countries/1
  # DELETE /countries/1.json
  def destroy
    @country.destroy
    respond_to do |format|
      format.html { redirect_to countries_url, notice: 'Country was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_country
      @country = Country.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def country_params
      params.require(:country).permit(:name, :iso_code_2, :iso_code_3)
    end
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/views/countries/_form.html.erb
<%= form_for(@country) do |f| %>
  <% if @country.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@country.errors.count, "error") %> prohibited this country from being saved:</h2>

      <ul>
      <% @country.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, :class=>"form-control" %>
  </div>
  <div class="field">
    <%= f.label :iso_code_2 %><br>
    <%= f.text_field :iso_code_2, :class=>"form-control" %>
  </div>
  <div class="field">
    <%= f.label :iso_code_3 %><br>
    <%= f.text_field :iso_code_3, :class=>"form-control" %>
  </div>
  <div class="actions">
    <%= f.submit :class=>"btn btn-primary" %>
    <%= button_tag "Reset", type: :reset, :class=>"btn btn-default"%>
  </div>
<% end %>

app/views/countries/edit.html.erb
<div class ="page-header">
  <%= link_to 'Show', @country, :class=> 'btn btn-primary pull-right'%>
  <%= link_to 'Back', countries_path, :class=> 'btn btn-default pull-right'%>
    <h3> Editing Countries</h3>
</div>

<%= render 'form' %>

app/views/countries/index.html.erb
<div class ="page-header">
  <%= link_to 'New Country', new_country_path, :class=> 'btn btn-success pull-right'%>
    <h3> Listing Countries</h3>
</div>

<table class="table table-striped table-responsive">
  <thead>
    <tr>
      <th>Name</th>
      <th>Iso code 2</th>
      <th>Iso code 3</th>
      <th ></th>
    </tr>
  </thead>

  <tbody>
    <% @countries.each do |country| %>
      <tr>
        <td><%= country.name %></td>
        <td><%= country.iso_code_2 %></td>
        <td><%= country.iso_code_3 %></td>
        <td>    
          <div class="btn-group">
            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Action <span class="caret"></span> </button>
              <ul class="dropdown-menu">
                <li><%= link_to 'Show', country %></li>
                <li><%= link_to 'Edit', edit_country_path(country) %></li>
                <li><%= link_to 'Delete', country, method: :delete, data: { confirm: 'Are you sure?' } %></li>
              </ul>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/countries/new.html.erb
<div class ="page-header">
  <%= link_to 'Back', countries_path, :class=> 'btn btn-default pull-right'%>
    <h3> New Country</h3>
</div>

<%= render 'form' %>

app/views/countries/show.html.erb
<div class ="page-header">
  <%= link_to 'Edit', edit_country_path(@country), :class=> 'btn btn-warning pull-right' %>
  <%= link_to 'Back', countries_path, :class=> 'btn btn-default pull-right' %>
  <h3> <%= @country.name %></h3>
</div>

  <!-- Table -->
  <table class="table table-striped table-responsive">
    
  <thead>
    <tr>
      <th>Iso code 2</th>
      <th>Iso code 3</th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= @country.iso_code_2 %></td>
        <td><%= @country.iso_code_3 %></td>
      </tr>
  </tbody>

  </table>