config/routes.rb
Rails.application.routes.draw do
  resources :events
  resources :events
  resources :vacancies
  resources :customers
  resources :countries
  root to: 'welcome#index'
  devise_for :users
  resources :users
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
<li><%= link_to 'Users', users_path %></li>
<li id="fat-menu" class="dropdown">
	<a href="#" class="dropdown-toggle glyphicon glyphicon-user" data-toggle="dropdown"> <b class="caret"></b></a>
	<ul class="dropdown-menu">
	  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
	  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
	</ul>
</li>
<% else %>
 <%= link_to 'Sign in', new_user_session_path, :class=> 'btn btn-default navbar-btn' %>
 <%= link_to 'Sign up', new_user_registration_path, :class=> 'btn btn-success navbar-btn' %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<div class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">

      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#collapsibleMenu">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <a href="/" class="navbar-brand">My Company</a>
    </div>

    <div class="collapse navbar-collapse" id ="collapsibleMenu">
      
      <ul class="nav navbar-nav navbar-left">
        <%= render 'layouts/navigation_links' %>
      </ul>

      <div>
      <ul class="nav navbar-nav navbar-right">
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>

      </div>
    </div>
  </div>
</div>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'About', page_path('about') %></li>

<% if user_signed_in? %>
	<li><%= link_to 'Timesheet', events_path %></li>
<% end %>

<% if current_user.try(:is_admin?) %>
	<li><%= link_to 'Countries', countries_path %></li>
	<li><%= link_to 'Customers', customers_path %></li>
	<li><%= link_to 'Vacancies', vacancies_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Timesheet" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Timesheet" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

  <%= render 'layouts/navigation' %>
  
  <div class="container">
    <%= render 'layouts/messages' %>
    <%= yield %>
  </div>
  

  </body>
</html>